FROM jwei/steamcmd:latest

ENV CONFIG_FILE /steamlibrary/serverconfig.xml
ENV CHECK_UPDATE 0

COPY start.sh /home/steam/start.sh

USER root
RUN set -x \
 && chown steam:steam /home/steam/start.sh \
 && chmod 755 /home/steam/start.sh
USER steam

CMD [ "/home/steam/start.sh" ]
